#include "XyzMeshWriter.h"
#include <iostream>
#include <fstream>

using namespace std;


XyzMeshWriter::XyzMeshWriter()
{
}


XyzMeshWriter::~XyzMeshWriter()
{
}

int XyzMeshWriter::writeDepthToMeshfile(const char* fileName, const unsigned char* depthData, const unsigned char* colorData, bool cullBlack, int width, int height){	
	float minX = -1.0f, maxX = 1.0f, minY = 1.0f, maxY = -1.0f, minZ = 0.0f, maxZ = 1.0f;
	ofstream  os;
	os.open(fileName, ios::out);
	int numPixels = width * height;
	int currPixel = 1;
	os << "#Generated by Depth2Mesh\n";
	while (currPixel <= numPixels){
		unsigned char z = *(depthData++);
		if (!(cullBlack && z == 0)){
			os << interpolate(minX, maxX, (currPixel > width ? (currPixel - (currPixel / width) * width) / (float)width : currPixel / (float)width));
			os << "\t";
			os << interpolate(minY, maxY, (currPixel > width ? (currPixel / width) / (float)height : 0.0f));
			os << "\t";
			os << interpolate(minZ, maxZ, z / 255.0f);
			os << "\n";
		}
		++currPixel;
	}
	os.close();
	return os.good();
}